### PR TITLE
Remove patch

### PR DESCRIPTION
**Pull request by goanpeca**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~[ ] Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by goanpeca** [comment]
Hi @hanjinliu, please do not merge this yet :) 

---

@jaimergp, since the package was never built and [uploaded](https://anaconda.org/conda-forge/magic-class) is ok to leave the version as `0`?

Also @hanjinliu updated the source code in the new release so the patch is no longer needed :)

**Comment by goanpeca** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Ummm this shouldn't have been merged, I think?

There's a new release that does not require the patch, but we built without the patch and the old version (version didn't change in this PR). Might need to mark it as broken and issue a new PR with the new version.

**Comment by goanpeca** [comment]
Hi @hanjinliu, [I asked you to not merge this PR in the message above](https://github.com/conda-forge/magic-class-feedstock/pull/3#issuecomment-1049290477).

Please be more careful the next time and make sure you read the comments addressed directly to you.

Also, you merged https://github.com/conda-forge/magic-class-feedstock/pull/2 which was not passing tests. Please do not merge a PR if the tests are not passing.

Cheers

**Pull request merged**
